In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
data=pd.read_csv('overfitting.csv')

In [5]:
X=data.loc[data.train==1,'var_1':].copy()
y=data.loc[data.train==1,'Target_Practice'].copy()

Xtest=data.loc[data.train==0,'var_1':].copy()
ytest=data.loc[data.train==0,'Target_Practice'].copy()

In [7]:
X.shape

(250, 200)

In [8]:
X.head()

,var_1,var_2,var_3,var_4,var_5,var_6,var_7,var_8,var_9,var_10,...,var_191,var_192,var_193,var_194,var_195,var_196,var_197,var_198,var_199,var_200
0,0.660,0.106,0.434,0.387,0.903,0.661,0.158,0.291,0.210,0.936,...,0.015,0.377,0.479,0.050,0.395,0.123,0.833,0.461,0.990,0.105
1,0.844,0.813,0.030,0.939,0.721,0.287,0.539,0.874,0.787,0.732,...,0.112,0.048,0.088,0.860,0.560,0.346,0.511,0.883,0.858,0.599
2,0.560,0.567,0.568,0.434,0.414,0.180,0.448,0.888,0.023,0.690,...,0.874,0.236,0.599,0.602,0.005,0.493,0.122,0.395,0.782,0.943
3,0.681,0.245,0.909,0.785,0.738,0.570,0.692,0.411,0.182,0.520,...,0.219,0.691,0.261,0.031,0.968,0.353,0.798,0.104,0.944,0.090
4,0.846,0.431,0.805,0.237,0.465,0.642,0.219,0.102,0.795,0.131,...,0.704,0.242,0.089,0.605,0.577,0.043,0.686,0.070,0.666,0.572